### ISSUE TITLE
problem related to  image url

### ISSUE THREAD

**Issue by engr-erum** [bsuhas/OCRTextRecognitionAndroidApp#1]
i have tried using google driver image link , imgur image link and dropbox link for image in case of first two i m getting error url is not correct while in case of dropbox i m getting error {"ParsedResults":[{"TextOverlay":null,"FileParseExitCode":-20,"ParsedText":"","ErrorMessage":"Timed out waiting for image parsing result or error generation by OCR","ErrorDetails":"Timed out waiting for processing images. Please retry"}],"OCRExitCode":3,"IsErroredOnProcessing":false,"ErrorMessage":null,"ErrorDetails":null,"ProcessingTimeInMilliseconds":"4140"}

please let me know how can  i upload images is any specific server required for image ?

**Comment by bsuhas** [comment]
@engr-erum  Hi, As mention google drive & dropbox image issue  both are of network & security issue
**1) In case of url is not correct** 
Your google drive image need public access  any one can access without credentials. 

**2) In case of dropbox** 
"Timed out waiting for image parsing result or error generation by OCR" it tells every thing. 

 **Q: How can I upload images is any specific server required for image ?**
Ans: No need of specific server, you can put any where but strictly  public access to that image required without any credentials . 

Hope your query get resolved, Still any let me know.

**Comment by engr-erum** [comment]
Pls help me this api is not reading text properly I have slip of grocery shop how can I read items and it's price from api

**Comment by engr-erum** [comment]
Place help me this api is not reading text properly I have slip of grocery shop how can I read items and it's price from api

**Comment by bsuhas** [comment]
Ya  I know API is sometime not reading text properly ( less efficient ) in that case you have to contact with  OCR Team **Email Id : ocrspace@a9t9.com** they will help  you .

**Comment by bsuhas** [comment]
@engr-erum  Ya  I know API is sometime not reading text properly ( less efficient ) in that case you have to contact with  OCR Team **Email Id : ocrspace@a9t9.com** they will help  you .

**Comment by engr-erum** [comment]
hi pls check email and respond me ASAP as it it required on urgent basis

**Comment by A9T9** [comment]
If you have a question about the OCR API itself, please contact us at
ocrspace AT a9t9.com

**Comment by chkrishna** [comment]
how to make json parse output from server into the TextView (output screen) for selected array list.
