### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by AbandonedCart** [bsuhas/OCRTextRecognitionAndroidApp#4]
I have a few pull requests that could vastly improve this app.

I have spoken to the staff at OCR.Space and can submit my repository as a replacement or submit the pull requests to this one. Either is acceptable for me.

**Comment by bsuhas** [comment]
Share your code repository with me, I will do the required things & let you know.

**Comment by AbandonedCart** [comment]
I apologize, but there is something suspicious about your request. I will discuss it with OCR.Space and get back to you.

**Comment by AbandonedCart** [comment]
I submitted the repository directly to OCR.Space with a rather extensive list of changes.

Thanks for you time.
